name: doit
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=3.7.1=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311ha68e1ae_3
  - arrow=1.2.3=pyhd8ed1ab_0
  - arrow-cpp=12.0.1=h2d54704_6_cpu
  - astor=0.8.1=pyh9f0ad1d_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - async-lru=2.0.3=pyhd8ed1ab_0
  - attrs=23.1.0=pyh71513ae_1
  - aws-c-auth=0.7.0=h6f3c987_2
  - aws-c-cal=0.6.0=h6ba3258_0
  - aws-c-common=0.8.23=hcfcfb64_0
  - aws-c-compression=0.2.17=h420beca_1
  - aws-c-event-stream=0.3.1=had47b81_1
  - aws-c-http=0.7.11=h72ba615_0
  - aws-c-io=0.13.28=ha35c040_0
  - aws-c-mqtt=0.8.14=h4941efa_2
  - aws-c-s3=0.3.13=he04eaa7_2
  - aws-c-sdkutils=0.1.11=h420beca_1
  - aws-checksums=0.1.16=h420beca_1
  - aws-crt-cpp=0.20.3=h247a981_4
  - aws-sdk-cpp=1.10.57=h1a0519f_17
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py311h1ea47a8_7
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - brotli=1.0.9=hcfcfb64_9
  - brotli-bin=1.0.9=hcfcfb64_9
  - brotli-python=1.0.9=py311h12c1d0e_9
  - bzip2=1.0.8=h8ffe710_4
  - c-ares=1.19.1=hcfcfb64_0
  - ca-certificates=2023.7.22=h56e8100_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py311h7d9ee11_3
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.1.0=py311h005e61a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - doit=0.36.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.2=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.9.0=pyhd8ed1ab_0
  - fonttools=4.41.1=py311ha68e1ae_0
  - formulaic=0.6.4=pyhd8ed1ab_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h546665d_1
  - gettext=0.21.1=h5728263_0
  - glib=2.76.4=h12be248_0
  - glib-tools=2.76.4=h12be248_0
  - graphlib-backport=1.0.3=pyhd8ed1ab_0
  - gst-plugins-base=1.22.5=h001b923_0
  - gstreamer=1.22.5=hb4038d2_0
  - holidays=0.29=pyhd8ed1ab_0
  - icu=72.1=h63175ca_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.0.0=pyhd8ed1ab_1
  - intel-openmp=2023.2.0=h57928b3_49496
  - interface_meta=1.3.0=pyhd8ed1ab_0
  - ipykernel=6.25.0=pyh6817e22_0
  - ipython=8.14.0=pyh08f2357_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=8.0.7=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.0=pyhd8ed1ab_1
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.0=py_0
  - jsonschema=4.18.4=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.18.4=pyhd8ed1ab_0
  - jupyter=1.0.0=py311h1ea47a8_8
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.0=pyhd8ed1ab_0
  - jupyter_console=6.6.3=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py311h1ea47a8_0
  - jupyter_events=0.6.3=pyhd8ed1ab_1
  - jupyter_server=2.7.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.3=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.24.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.8=pyhd8ed1ab_0
  - jupytext=1.14.7=pyh5da7574_0
  - keras=2.13.1=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py311h005e61a_1
  - krb5=1.21.1=heb0366b_0
  - lcms2=2.15=h3e3b177_1
  - lerc=4.0.0=h63175ca_0
  - libabseil=20230125.3=cxx17_h63175ca_0
  - libarrow=12.0.1=h0578746_6_cpu
  - libblas=3.9.0=17_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.9.0=17_win64_mkl
  - libclang=15.0.7=default_h77d9078_2
  - libclang13=15.0.7=default_h77d9078_2
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.2.1=hd5e4a3a_0
  - libdeflate=1.18=hcfcfb64_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.2=h8ffe710_5
  - libglib=2.76.4=he8f3873_0
  - libgoogle-cloud=2.12.0=hbc1b25b_1
  - libgrpc=1.56.2=hea2d5f7_0
  - libhwloc=2.9.2=nocuda_h15da153_1008
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.5.1=hcfcfb64_0
  - liblapack=3.9.0=17_win64_mkl
  - libogg=1.3.4=h8ffe710_1
  - libpng=1.6.39=h19919ed_0
  - libprotobuf=4.23.3=h1975477_0
  - libsodium=1.0.18=h8d14728_1
  - libsqlite=3.42.0=hcfcfb64_0
  - libssh2=1.11.0=h7dfc565_0
  - libthrift=0.18.1=h06f6336_2
  - libtiff=4.5.1=h6c8260b_0
  - libutf8proc=2.8.0=h82a8f57_0
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.3.1=hcfcfb64_0
  - libxcb=1.15=hcd874cb_0
  - libxml2=2.11.4=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - linearmodels=5.1=py311h59ca53f_0
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.4.4=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py311ha68e1ae_0
  - matplotlib=3.7.2=py311h1ea47a8_0
  - matplotlib-base=3.7.2=py311h6e989c2_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdit-py-plugins=0.4.0=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=3.0.0=pyhd8ed1ab_0
  - mizani=0.9.2=pyhd8ed1ab_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert=7.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.7.3=pyhd8ed1ab_0
  - nbconvert-pandoc=7.7.3=pyhd8ed1ab_0
  - nbformat=5.9.1=pyhd8ed1ab_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=7.0.0=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - numpy=1.25.1=py311h0b4df5a_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=3.1.1=hcfcfb64_1
  - orc=1.9.0=hf2b8f0d_1
  - overrides=7.3.1=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py311hf63dbb6_1
  - pandoc=3.1.3=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=h17e33f8_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.0=py311hde623f7_0
  - pip=23.2.1=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.9.1=pyhd8ed1ab_0
  - plotly=5.15.0=pyhd8ed1ab_0
  - plotnine=0.12.2=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py311ha68e1ae_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=12.0.1=py311h6a6099b_6_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyhdfe=0.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.9=py311h125bc19_4
  - pyqt5-sip=12.12.2=py311h12c1d0e_4
  - pysocks=1.7.1=pyh0701188_6
  - python=3.11.4=h2628c8c_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pywin32=304=py311h12c1d0e_2
  - pywinpty=2.0.11=py311h12c1d0e_0
  - pyyaml=6.0=py311ha68e1ae_5
  - pyzmq=25.1.0=py311h7b3f143_0
  - qt-main=5.15.8=h063a7da_15
  - qtconsole=5.4.3=pyhd8ed1ab_0
  - qtconsole-base=5.4.3=pyha770c72_0
  - qtpy=2.3.1=pyhd8ed1ab_0
  - re2=2023.03.02=hd4eee63_0
  - referencing=0.30.0=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.9.2=py311hc37eb10_0
  - scikit-learn=1.3.0=py311h142b183_0
  - scipy=1.11.1=py311h37ff6ca_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - send2trash=1.8.2=pyh08f2357_0
  - setuptools=68.0.0=pyhd8ed1ab_0
  - sip=6.7.10=py311h12c1d0e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=hfb803bf_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.42.0=hcfcfb64_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - statsmodels=0.14.0=py311h59ca53f_1
  - tbb=2021.10.0=h91493d7_0
  - tenacity=8.2.2=pyhd8ed1ab_0
  - terminado=0.17.0=pyh08f2357_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h8ffe710_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.3.2=py311ha68e1ae_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ucrt=10.0.22621.0=h57928b3_0
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=2.0.4=pyhd8ed1ab_0
  - vc=14.3=h64f974e_17
  - vc14_runtime=14.36.32532=hfdfe4a8_17
  - vs2015_runtime=14.36.32532=h05e6639_17
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.6.1=pyhd8ed1ab_0
  - wheel=0.41.0=pyhd8ed1ab_0
  - widgetsnbextension=4.0.8=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - winpty=0.4.3=4
  - wrapt=1.15.0=py311ha68e1ae_0
  - xlsxwriter=3.1.2=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zstd=1.5.2=h12be248_7
  - pip:
    - ply==3.11
    - tensorboard==2.10.1
prefix: C:\Users\Jeremy\miniconda3\envs\doit
